# Use common project's makefile tools.
include common.mk

# Main target. Build interface library.
main:
	@echo "$@: Not implemented yet."

# Generate C++ source and header files based on *.proto files.
generate:
	@$(PBC) --cpp_out=. *.proto

# Remove all build artifacts and ProtoBuf generated sources and headers.
clean:
	@$(RM) *.pb.*

# Install built library in target location.
install:
	@echo "$@: Not implemented yet."
